// <auto-generated />
using System;
using CocktailsApp.Infrastructure.SeedWork;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CocktailsApp.Infrastructure.Migrations.EFReadDb
{
    [DbContext(typeof(EFReadDbContext))]
    [Migration("20250813035601_FixIssue1")]
    partial class FixIssue1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CocktailsApp.Application.Club.ClubRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ClubRead");
                });

            modelBuilder.Entity("CocktailsApp.Application.Cocktail.CocktailRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CocktailRead");
                });

            modelBuilder.Entity("CocktailsApp.Application.Ingredient.IngredientRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Allergens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("IngredientRead");
                });

            modelBuilder.Entity("CocktailsApp.Application.IngredientPricing.IngredientPricingRead", b =>
                {
                    b.Property<Guid>("IngredientPricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ImageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<decimal>("Margin")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IngredientPricingId");

                    b.ToTable("IngredientPricingRead");
                });

            modelBuilder.Entity("CocktailsApp.Application.Order.OrderRead", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("OrderId");

                    b.ToTable("OrderRead");
                });

            modelBuilder.Entity("CocktailsApp.Application.Stock.StockRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("StockRead");
                });

            modelBuilder.Entity("CocktailsApp.Application.User.UserRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UserRead");
                });

            modelBuilder.Entity("CocktailsApp.Application.Club.ClubRead", b =>
                {
                    b.OwnsOne("CocktailsApp.Application.Club.ClubAddressRead", "Address", b1 =>
                        {
                            b1.Property<Guid>("ClubReadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("ClubReadId");

                            b1.ToTable("ClubRead");

                            b1.WithOwner()
                                .HasForeignKey("ClubReadId");
                        });

                    b.OwnsMany("CocktailsApp.Application.Club.ClubCocktailRead", "Cocktails", b1 =>
                        {
                            b1.Property<Guid>("ClubReadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ClubCocktailId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CocktailId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("ImageId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("ClubReadId", "Id");

                            b1.ToTable("ClubCocktailRead");

                            b1.WithOwner()
                                .HasForeignKey("ClubReadId");

                            b1.OwnsMany("CocktailsApp.Application.Club.ClubCocktailIngredientRead", "Ingredients", b2 =>
                                {
                                    b2.Property<Guid>("ClubCocktailReadClubReadId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("ClubCocktailReadId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.PrimitiveCollection<string>("Allergens")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ImageId")
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<Guid>("IngredientId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<bool>("IsAlcoholic")
                                        .HasColumnType("bit");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<decimal>("Quantity")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)");

                                    b2.HasKey("ClubCocktailReadClubReadId", "ClubCocktailReadId", "Id");

                                    b2.ToTable("ClubCocktailIngredientRead");

                                    b2.WithOwner()
                                        .HasForeignKey("ClubCocktailReadClubReadId", "ClubCocktailReadId");
                                });

                            b1.Navigation("Ingredients");
                        });

                    b.OwnsMany("CocktailsApp.Application.Club.ClubMemberRead", "Members", b1 =>
                        {
                            b1.Property<Guid>("ClubReadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ClubMemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("ClubReadId", "Id");

                            b1.ToTable("ClubMemberRead");

                            b1.WithOwner()
                                .HasForeignKey("ClubReadId");

                            b1.OwnsMany("CocktailsApp.Application.Club.ClubRoleRead", "Roles", b2 =>
                                {
                                    b2.Property<Guid>("ClubMemberReadClubReadId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("ClubMemberReadId")
                                        .HasColumnType("int");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)");

                                    b2.PrimitiveCollection<string>("Permissions")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ClubMemberReadClubReadId", "ClubMemberReadId", "Id");

                                    b2.ToTable("ClubMemberRead_Roles");

                                    b2.WithOwner()
                                        .HasForeignKey("ClubMemberReadClubReadId", "ClubMemberReadId");
                                });

                            b1.Navigation("Roles");
                        });

                    b.OwnsMany("CocktailsApp.Application.Club.ClubRoleRead", "Roles", b1 =>
                        {
                            b1.Property<Guid>("ClubReadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.PrimitiveCollection<string>("Permissions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClubReadId", "Id");

                            b1.ToTable("ClubRead_Roles");

                            b1.WithOwner()
                                .HasForeignKey("ClubReadId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Cocktails");

                    b.Navigation("Members");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("CocktailsApp.Application.Cocktail.CocktailRead", b =>
                {
                    b.OwnsMany("CocktailsApp.Application.Cocktail.CocktailIngredientRead", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("CocktailReadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.PrimitiveCollection<string>("Allergens")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("CocktailIngredientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ImageId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid>("IngredientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsAlcoholic")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CocktailReadId", "__synthesizedOrdinal");

                            b1.ToTable("CocktailRead");

                            b1.ToJson("Ingredients");

                            b1.WithOwner()
                                .HasForeignKey("CocktailReadId");
                        });

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CocktailsApp.Application.Order.OrderRead", b =>
                {
                    b.OwnsMany("CocktailsApp.Application.Order.OrderItemRead", "Items", b1 =>
                        {
                            b1.Property<Guid>("OrderReadOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<Guid>("CocktailId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Descritpion")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("ImageId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("OrderReadOrderId", "__synthesizedOrdinal");

                            b1.ToTable("OrderRead");

                            b1.ToJson("Items");

                            b1.WithOwner()
                                .HasForeignKey("OrderReadOrderId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("CocktailsApp.Application.Stock.StockRead", b =>
                {
                    b.OwnsMany("CocktailsApp.Application.Stock.StockTransactionDTO", "Transactions", b1 =>
                        {
                            b1.Property<Guid>("StockReadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<string>("TransactionType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("StockReadId", "__synthesizedOrdinal");

                            b1.ToTable("StockRead");

                            b1.ToJson("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("StockReadId");
                        });

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
