<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AnalysisLevel>latest</AnalysisLevel>
	<Configurations>Debug;Release;LOCAL;LOCAL-COGNITO</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
	<Analyzer Include="..\Analyzers\bin\Debug\netstandard2.0\Analyzers.dll" />
      <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
          <_Parameter1>Domain.Tests</_Parameter1>
      </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ClubAggregate\Services\" />
    <Folder Include="StockAggregate\Services\" />
  </ItemGroup>
</Project>
