<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <AnalyzerRulesVersion>latest</AnalyzerRulesVersion>
    <Configurations>Debug;Release;LOCAL-COGNITO</Configurations>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
     <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CodesFixes\" />
    <Folder Include="Helpers\" />
  </ItemGroup>

</Project>
