// <auto-generated />
using System;
using System.Collections.Generic;
using CocktailsApp.Infrastructure.SeedWork;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20250728230317_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubMember_Roles", b =>
                {
                    b.Property<Guid>("ClubRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClubRoleId", "ClubMemberId");

                    b.HasIndex("ClubMemberId");

                    b.ToTable("ClubMember_Roles");
                });

            modelBuilder.Entity("CocktailsApp.Domain.ClubAggregate.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "CocktailsApp.Domain.ClubAggregate.Club.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("CocktailsApp.Domain.ClubAggregate.ClubCocktail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CocktailId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("CocktailId");

                    b.ToTable("ClubCocktail");
                });

            modelBuilder.Entity("CocktailsApp.Domain.ClubAggregate.ClubMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasFilter("[OwnerId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("ClubMember");
                });

            modelBuilder.Entity("CocktailsApp.Domain.ClubAggregate.ClubRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOwnerRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("ClubRole");
                });

            modelBuilder.Entity("CocktailsApp.Domain.CocktailAggregate.Cocktail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cocktail");
                });

            modelBuilder.Entity("CocktailsApp.Domain.IngredientPricingAggregate.IngredientPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.ComplexProperty<Dictionary<string, object>>("Ingredient", "CocktailsApp.Domain.IngredientPricingAggregate.IngredientPricing.Ingredient#Ingredient", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("IngredientPricing");
                });

            modelBuilder.Entity("CocktailsApp.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CocktailsApp.Domain.OrderAggregate.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CocktailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CocktailId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("CocktailsApp.Domain.StockAggregate.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty<Dictionary<string, object>>("Ingredient", "CocktailsApp.Domain.StockAggregate.Stock.Ingredient#Ingredient", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("CocktailsApp.Domain.StockAggregate.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockTransaction");
                });

            modelBuilder.Entity("CocktailsApp.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ClubMember_Roles", b =>
                {
                    b.HasOne("CocktailsApp.Domain.ClubAggregate.ClubMember", "ClubMember")
                        .WithMany()
                        .HasForeignKey("ClubMemberId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("CocktailsApp.Domain.ClubAggregate.ClubRole", "ClubRole")
                        .WithMany()
                        .HasForeignKey("ClubRoleId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ClubMember");

                    b.Navigation("ClubRole");
                });

            modelBuilder.Entity("CocktailsApp.Domain.ClubAggregate.ClubCocktail", b =>
                {
                    b.HasOne("CocktailsApp.Domain.ClubAggregate.Club", null)
                        .WithMany("Cocktails")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailsApp.Domain.CocktailAggregate.Cocktail", null)
                        .WithMany()
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CocktailsApp.Domain.ClubAggregate.ClubMember", b =>
                {
                    b.HasOne("CocktailsApp.Domain.ClubAggregate.Club", null)
                        .WithMany("Members")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailsApp.Domain.ClubAggregate.Club", null)
                        .WithOne("Owner")
                        .HasForeignKey("CocktailsApp.Domain.ClubAggregate.ClubMember", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CocktailsApp.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("CocktailsApp.Domain.ClubAggregate.ClubPermission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("ClubMemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Permission")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClubMemberId", "Id");

                            b1.ToTable("ClubMember_Permissions");

                            b1.WithOwner()
                                .HasForeignKey("ClubMemberId");
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CocktailsApp.Domain.ClubAggregate.ClubRole", b =>
                {
                    b.HasOne("CocktailsApp.Domain.ClubAggregate.Club", null)
                        .WithMany("Roles")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("CocktailsApp.Domain.ClubAggregate.ClubPermission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("ClubRoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Permission")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClubRoleId", "Id");

                            b1.ToTable("ClubRole_Permissions");

                            b1.WithOwner()
                                .HasForeignKey("ClubRoleId");
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CocktailsApp.Domain.CocktailAggregate.Cocktail", b =>
                {
                    b.OwnsMany("CocktailsApp.Domain.CocktailAggregate.CocktailIngredient", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("CocktailId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.HasKey("CocktailId", "Id");

                            b1.ToTable("CocktailIngredient");

                            b1.WithOwner()
                                .HasForeignKey("CocktailId");
                        });

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CocktailsApp.Domain.OrderAggregate.Order", b =>
                {
                    b.HasOne("CocktailsApp.Domain.ClubAggregate.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailsApp.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CocktailsApp.Domain.OrderAggregate.OrderItem", b =>
                {
                    b.HasOne("CocktailsApp.Domain.CocktailAggregate.Cocktail", null)
                        .WithMany()
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailsApp.Domain.OrderAggregate.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailsApp.Domain.StockAggregate.StockTransaction", b =>
                {
                    b.HasOne("CocktailsApp.Domain.StockAggregate.Stock", null)
                        .WithMany("StockTransactions")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailsApp.Domain.ClubAggregate.Club", b =>
                {
                    b.Navigation("Cocktails");

                    b.Navigation("Members");

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("CocktailsApp.Domain.OrderAggregate.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CocktailsApp.Domain.StockAggregate.Stock", b =>
                {
                    b.Navigation("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
