# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - 'dev*'
  pull_request:
    branches: [ "dev" ]



jobs:
  lint:
    uses: ./.github/workflows/components/lint.yml

  build:
    uses: ./.github/workflows/components/build.yml 

  tests:
    uses: ./.github/workflows/components/tests.yml 

  documentation:
    uses: ./.github/workflows/components/documentation.yml 

  deploy:
    needs: [tests, documentation]
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download Documentation
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: deployment

      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: deployment/coverage      

      - name: Upload Documentation & Coverage
        uses: actions/upload-pages-artifact@v3
        with:
          path: deployment

      - name: Deploy documentation to GitHub Pages
        id: deploy-documentation
        uses: actions/deploy-pages@v4
