<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<GenerateDocumentationFile>false</GenerateDocumentationFile>
	<Configurations>Debug;Release;LOCAL;LOCAL-COGNITO</Configurations>
    <AssemblyName>CocktailsApp.Application</AssemblyName>
    <RootNamespace>CocktailsApp.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Cocktails\Queries\" />
    <Folder Include="Ingredients\Queries\" />
    <Folder Include="Order\Commands\" />
    <Folder Include="Order\DTOs\" />
    <Folder Include="Order\Queries\" />
    <Folder Include="Prices\DTOs\" />
    <Folder Include="Prices\Commands\" />
    <Folder Include="Prices\Queries\" />
    <Folder Include="Stock\Commands\" />
    <Folder Include="Stock\DTOs\" />
    <Folder Include="Stock\Queries\" />
    <Folder Include="Users\Commands\" />
  </ItemGroup>

</Project>
