name: Setup .NET Project
description: Common steps like checkout, dotnet install

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build & pack analyzers
      run: dotnet pack src/Analyzers/Analyzers.csproj --configuration Release
      shell: bash

    - name: Add local NuGet source
      run: dotnet nuget add source ./nupkgs --name local
      shell: bash

    - name: Setup dependencies
      run: dotnet restore
      shell: bash
