// <auto-generated />
using System;
using CocktailsApp.ReadStore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CocktailsApp.ReadStore._Persistence.Migrations
{
    [DbContext(typeof(EFReadDbContext))]
    [Migration("20250815171047_AddedKafka")]
    partial class AddedKafka
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubCocktailRead", b =>
                {
                    b.Property<Guid>("ClubCocktailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CocktailId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClubCocktailId");

                    b.HasIndex("ClubCocktailId");

                    b.HasIndex("ClubId");

                    b.HasIndex("CocktailId");

                    b.ToTable("ClubCocktailRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubMemberRead", b =>
                {
                    b.Property<Guid>("ClubMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClubMemberId");

                    b.HasIndex("ClubId");

                    b.HasIndex("ClubMemberId");

                    b.HasIndex("UserId");

                    b.ToTable("ClubMemberRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubMemberRoleRead", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOwnerRole")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClubId", "ClubMemberId", "RoleId");

                    b.HasIndex("ClubId");

                    b.HasIndex("ClubMemberId");

                    b.HasIndex("RoleId");

                    b.ToTable("ClubMemberRoleRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubRead", b =>
                {
                    b.Property<Guid>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClubId");

                    b.HasIndex("ClubId");

                    b.ToTable("ClubRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubRolePermissionRead", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "Permission");

                    b.HasIndex("ClubId");

                    b.HasIndex("RoleId");

                    b.ToTable("ClubRolePermissionRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubRoleRead", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOwnerRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RoleId");

                    b.HasIndex("ClubId");

                    b.HasIndex("RoleId");

                    b.ToTable("ClubRoleRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Cocktails.CocktailIngredientRead", b =>
                {
                    b.Property<Guid>("CocktailIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CocktailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IngredientType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CocktailIngredientId");

                    b.HasIndex("CocktailId");

                    b.HasIndex("CocktailIngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CocktailIngredientRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Cocktails.CocktailRead", b =>
                {
                    b.Property<Guid>("CocktailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CocktailId");

                    b.HasIndex("CocktailId");

                    b.ToTable("CocktailRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Common.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint");

                    b.Property<int>("Partition")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedEvent");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Ingredients.AllergenRead", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IngredientId", "Name");

                    b.HasIndex("IngredientId");

                    b.ToTable("AllergenRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Ingredients.IngredientRead", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IngredientType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Users.UserSummaryRead", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSummaryRead");
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubCocktailRead", b =>
                {
                    b.HasOne("CocktailsApp.ReadStore.Clubs.ClubRead", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailsApp.ReadStore.Cocktails.CocktailRead", null)
                        .WithMany()
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubMemberRead", b =>
                {
                    b.HasOne("CocktailsApp.ReadStore.Clubs.ClubRead", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailsApp.ReadStore.Users.UserSummaryRead", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubMemberRoleRead", b =>
                {
                    b.HasOne("CocktailsApp.ReadStore.Clubs.ClubRead", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CocktailsApp.ReadStore.Clubs.ClubMemberRead", null)
                        .WithMany()
                        .HasForeignKey("ClubMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailsApp.ReadStore.Clubs.ClubRoleRead", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubRolePermissionRead", b =>
                {
                    b.HasOne("CocktailsApp.ReadStore.Clubs.ClubRead", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CocktailsApp.ReadStore.Clubs.ClubRoleRead", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Clubs.ClubRoleRead", b =>
                {
                    b.HasOne("CocktailsApp.ReadStore.Clubs.ClubRead", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CocktailsApp.ReadStore.Ingredients.AllergenRead", b =>
                {
                    b.HasOne("CocktailsApp.ReadStore.Ingredients.IngredientRead", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
