name: Build

on:
  workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Setup .NET
              uses: .github/actions/setup-dotnet/action.yml

            - name: Build
              run: dotnet build --configuration Debug --no-restore -p:TreatWarningsAsErrors=true -p:EnforceCodeStyleInBuild=true 