# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - 'dev*'
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup dependencies
        run: |
            dotnet restore
            dotnet tool install -g dotnet-format

      - name: Lint
        run: dotnet format style --verify-no-changes --verbosity diagnostic --report './lint-report.json'

      - name: Upload Lint Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: ./lint-report.json

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -p:TreatWarningsAsErrors=true -p:EnforceCodeStyleInBuild=true

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup dependencies
        run: |
          dotnet restore
          dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Test with Coverage
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Generate Coverage Report
        run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage -reporttypes:Html

      - name: Upload Coverage Report
        uses: actions/upload-pages-artifact@v3
        with:
          name: coverage-report
          path: coverage

  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup dependencies
        run: |
          dotnet restore
          dotnet tool install -g docfx

      - name: Generate Documentation
        run: docfx docs/docfx.json

      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v3
        with:
          name: documentation
          path: docs/_site

  deploy:
    needs: [tests, documentation]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy coverage to GitHub Pages
        id: deploy-coverage
        uses: actions/deploy-pages@v4
        with:
          artifact_name: coverage-report
          target_branch: ${{ github.ref == 'refs/heads/main' && 'gh-pages-prod' || 'gh-pages-dev' }}

      - name: Deploy documentation to GitHub Pages
        id: deploy-documentation
        uses: actions/deploy-pages@v4
        with:
          artifact_name: documentation
          target_branch: ${{ github.ref == 'refs/heads/main' && 'gh-pages-prod' || 'gh-pages-dev' }}
